### ISSUE TITLE
Figure 13 colours

### ISSUE THREAD

**Issue by Jennifer-Boldt** [rooperc4/ForageFishLitReview#2]
This seems to work for the figure - to get white colour for zeros. But we can see when more data is in the 'database'
ggplot(pressure_data, aes(x=outcome, y=pressure, col = count, fill = count, label = count)) +
  geom_tile() +
  geom_text(col = "black") +
  theme_minimal() +
  scale_fill_gradient2(low = "white", high = "red") +
  scale_color_gradient2(low = "white", high = "red")

**Comment by rooperc4** [comment]
I added your code to the figure section.
